[package]
name = "sgen"
version = "0.0.1"
authors = ["Henrik Rydgård"]
edition = "2021"

[dependencies]
markdown = "1.0.0-alpha.16"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
handlebars = "5.0"
env_logger = "0.10"
axum = "0.7.3"
axum-extra = "0.9.1"
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5.0", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
